import React from "react";
import type { Metadata } from "next";

import { NotFound, RedirectToHome } from "@/components/common";
import {
  HomeStack,
  ExerciseStack,
  WorkoutStack,
  ProfileStack,
} from "@/components/screens";

interface Props {
  params: Promise<{
    slug: string;
  }>;
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}

export async function generateMetadata({
  params,
  searchParams,
}: Props): Promise<Metadata> {
  const page = (await params).slug[0];
  return {
    title: `Fitness - ${page}`,
    description: "Generated by create next app",
  };
}

const Page = async ({ params, searchParams }: Props) => {
  const page = (await params).slug[0];

  switch (page) {
    case "home":
      return <HomeStack />;
    case "workout":
      return <WorkoutStack />;
    case "catalog":
      return <ExerciseStack />;
    case "profile":
      return <ProfileStack />;
    default:
      return <NotFound />;
  }
  // return page === "about" ? <RedirectToHome /> : <NotFound />;
};

export default Page;
